### ISSUE TITLE
Catkin make failure with gpu version of opencv

### ISSUE THREAD

**Issue by YoshiRi** [daniel-dsouza/solid-succotash#1]
Hi daniel.

I read your issue [ros_answer](https://answers.ros.org/question/242376/having-trouble-using-cuda-enabled-opencv-with-kinetic/?answer=242935#post-id-242935) and I am also struggling with similar problem.

I have opencv3.1 with cuda8.0 in ubuntu16 and ros kinetic. OpenCV with cuda itself works well but not in ROS.
So, I tried to make your source with catkin_make, but I got following errors:

```
CMakeFiles/face_learn_node.dir/src/face_learn.cpp.o: In function `FaceLearn::FaceLearn(ros::NodeHandle)':
face_learn.cpp:(.text+0x1700): undefined reference to `cv::cuda::CascadeClassifier::create(cv::String const&)'
collect2: error: ld returned 1 exit status
solid-succotash/CMakeFiles/face_learn_node.dir/build.make:234: recipe for target '/home/ubuntu/catkin_ws/devel/lib/face_learn/face_learn_node' failed
make[2]: *** [/home/ubuntu/catkin_ws/devel/lib/face_learn/face_learn_node] Error 1
CMakeFiles/Makefile2:2332: recipe for target 'solid-succotash/CMakeFiles/face_learn_node.dir/all' failed
make[1]: *** [solid-succotash/CMakeFiles/face_learn_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This may be because my opencv library with cuda is not added to ${OpenCV_LIBS}.
So if I added 'opencv_cudaobject' manually and it can be built with no error.
Looks like following.
```
target_link_libraries(face_learn_node
  ${OpenCV_LIBS}
  ${catkin_LIBRARIES} opencv_cudaobjdetect
)
```

Finally when I run your roslaunch files, it still yield GPU is not found.
```
[ERROR] [1507787540.490264122]: No GPU found!
```
So, do you know any other possibilities to fix this problem? 

Thank you!

P.S.
Here show some of my path. 
```
echo $CMAKE_PREFIX_PATH 
/usr/local:/home/ubuntu/catkin_ws/devel:/opt/ros/kinetic

echo $LD_LIBRARY_PATH 
/usr/local/lib:/home/ubuntu/catkin_ws/devel/lib:/usr/local/lib:/opt/ros/kinetic/lib:/usr/local/cuda/lib64
```

**Comment by daniel-dsouza** [comment]
This might be very late, but please check this as well - https://github.com/daniel-dsouza/vision_opencv
ROS requires some extra work to work with custom (CUDA enabled) installations of OpenCV.
